version: "2"
services:
  chart_data:
    build: ./chart_data
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - "5000:5000"
    volumes:
      - ./chart_data:/chart_data
